version: '3.3'
services:
  btb_db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'laravel'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    command: --init-file /init.sql
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./init.sql:/init.sql

  #btb_adminer:
      #image: adminer
      #restart: always
      #ports:
          #- 8080:8080
# Names our volume
volumes:
  my-db:
